### ISSUE TITLE
Cannot find module 'core-js/modules/es6.regexp.split'

### ISSUE THREAD

**Issue by jonathanmach** [storyblok/gridsome-source-storyblok#15]
Hi, I keep getting the `Cannot find module 'core-js/modules/es6.regexp.split'` error when trying to use this plugin.

```
> gridsome develop

Gridsome v0.7.13

Initializing plugins...
Error: Cannot find module 'core-js/modules/es6.regexp.split'
Require stack:
- C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\storyblok-js-client\dist\index.js
- C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\gridsome-source-storyblok\index.js
- C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\gridsome\lib\app\Plugins.js
- C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\gridsome\lib\app\App.js
- C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\gridsome\lib\app\index.js
- C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\gridsome\lib\develop.js
- C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\gridsome\index.js
- C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\gridsome\node_modules\@gridsome\cli\bin\gridsome.js      
- C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\gridsome\bin\gridsome.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\storyblok-js-client\dist\index.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\jonat\Desktop\Projects\Code Projects\Websites\rosemary-hale-gridsome\node_modules\gridsome-source-storyblok\index.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rosemary-hale-gridsome@ develop: `gridsome develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rosemary-hale-gridsome@ develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by emanuelgsouza** [comment]
There was a problem with the versions of core-js between our plugin and Gridsome. The last version ([v0.3.0](https://github.com/storyblok/gridsome-source-storyblok/releases/tag/v0.3.0)) fix this.

**Comment by jonathanmach** [comment]
Awesome, thanks!
